language: generic  # use "generic" since you're using Docker, not Ruby
os: linux
dist: xenial
services: 
  - docker

env:
  - CI=true

before_install:
  - docker build -t akhilakadem/frontend -f Dockerfile.dev .

script:
  - docker run  akhilakadem/frontend npm run test -- --coverage

#deploy:
 # provider: elasticbeanstalk
#  region: "us-east-1"
 # app: "frontend"
 # env: "Frontend-env"
 # bucket_name: "elasticbeanstalk-us-east-1-103572352910"
 # bucket_path: "frontend"
  #on:
  #  branch: main