language: generic  # use "generic" since you're using Docker, not Ruby
dist: focal
os: linux
dist: xenial
services: 
  - docker

env:
  - CI=true

before_install:
  - docker build -t akhilakadem/frontend -f Dockerfile.dev .

script:
  - docker run --rm akhilakadem/frontend npm test -- --coverage --watchAll=false


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-103572352910"
  bucket_path: "frontend"
  
  on:
    branch: main
  access_key_id: "AWS_ACCESS_KEY"
  secret_access_key: "AWS_SECRET_KEY"