sudo : required
services: 
  - docker

env:
  - CI=true

before_install:
  - docker build -t Akhila-Kadem/Frontend -f Dockerfile.dev .

script:
  - docker run Akhila-Kadem/Frontend npm run test -- -- coverage
